import express from 'express';
import pg from 'pg';
import crypto from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const {Pool}=pg;
const app=express();
const port=Number(process.env.PORT||3000);
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:20,idleTimeoutMillis:30000,connectionTimeoutMillis:5000});
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const publicDir=path.join(__dirname,'../public');
const secret=process.env.JWT_SECRET||'dev-only-change-this-secret';

app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'");next()});
app.use(express.json({limit:'256kb'}));
app.use(express.urlencoded({extended:false,limit:'64kb'}));
app.use((req,res,next)=>{let n=Number(req.app.locals.rate?.get(req.ip)||0)+1;if(!req.app.locals.rate)req.app.locals.rate=new Map();req.app.locals.rate.set(req.ip,n);if(n>300){return res.status(429).json({error:'rate_limit'});}setTimeout(()=>req.app.locals.rate?.delete(req.ip),60000);next()});
app.use(express.static(publicDir,{extensions:['html'],maxAge:process.env.NODE_ENV==='production'?'1h':0}));

const b64=v=>Buffer.from(v).toString('base64url');
function signToken(payload){const head=b64(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=b64(JSON.stringify({...payload,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+86400}));const sig=b64(crypto.createHmac('sha256',secret).update(`${head}.${body}`).digest());return `${head}.${body}.${sig}`}
function verifyToken(token){try{const [h,p,s]=token.split('.');const expected=b64(crypto.createHmac('sha256',secret).update(`${h}.${p}`).digest());if(!s||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null;const x=JSON.parse(Buffer.from(p,'base64url'));return x.exp>Date.now()/1000?x:null}catch{return null}}
function hashPassword(password){const salt=crypto.randomBytes(16);const hash=crypto.scryptSync(password,salt,64);return `scrypt:${salt.toString('hex')}:${hash.toString('hex')}`}
function checkPassword(password,stored){try{const [,saltHex,hashHex]=stored.split(':');const hash=crypto.scryptSync(password,Buffer.from(saltHex,'hex'),64);return crypto.timingSafeEqual(hash,Buffer.from(hashHex,'hex'))}catch{return false}}
const clean=(v,max=500)=>String(v??'').trim().slice(0,max);
const email=v=>clean(v,254).toLowerCase();
async function q(text,params=[]){return pool.query(text,params)}
async function audit(req,action,entity,id,metadata={}){if(!req.user)return;await q('INSERT INTO audit_log(organization_id,user_id,action,entity,entity_id,metadata,ip) VALUES($1,$2,$3,$4,$5,$6,$7)',[req.user.org,req.user.id,action,entity,id,metadata,req.ip]).catch(()=>{})}
function auth(req,res,next){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=verifyToken(token);if(!u)return res.status(401).json({error:'unauthorized'});req.user=u;next()}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'forbidden'})}

app.get('/healthz',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'jarastay',time:new Date().toISOString()})}catch{res.status(503).json({ok:false})}});
app.get('/api/public/properties/:slug',async(req,res)=>{const r=await q('SELECT p.id,p.name,p.slug,p.address,p.check_in,p.check_out,rt.id room_type_id,rt.name room_type,rt.description,rt.capacity,rt.base_rate FROM properties p JOIN room_types rt ON rt.property_id=p.id WHERE p.slug=$1 AND p.active=true AND rt.active=true ORDER BY rt.name',[req.params.slug]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json({property:r.rows[0]&&{id:r.rows[0].id,name:r.rows[0].name,slug:r.rows[0].slug,address:r.rows[0].address,checkIn:r.rows[0].check_in,checkOut:r.rows[0].check_out},roomTypes:r.rows.map(x=>({id:x.room_type_id,name:x.room_type,description:x.description,capacity:x.capacity,baseRate:Number(x.base_rate)}))})});

app.post('/api/auth/register',async(req,res)=>{const name=clean(req.body.name,120),em=email(req.body.email),password=String(req.body.password||'');if(name.length<2||!em.includes('@')||password.length<10)return res.status(400).json({error:'invalid_input'});const slug=(clean(req.body.hotelName,80)||'hotel').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+crypto.randomBytes(3).toString('hex');const client=await pool.connect();try{await client.query('BEGIN');const org=(await client.query('INSERT INTO organizations(name,slug) VALUES($1,$2) RETURNING *',[clean(req.body.hotelName,120)||'Meu Hotel',slug])).rows[0];const user=(await client.query('INSERT INTO users(organization_id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role',[org.id,name,em,hashPassword(password),'owner'])).rows[0];const prop=(await client.query('INSERT INTO properties(organization_id,name,slug,address) VALUES($1,$2,$3,$4) RETURNING id,name,slug',[org.id,org.name,slug,JSON.stringify({country:'BR'})])).rows[0];await client.query('COMMIT');const token=signToken({id:user.id,org:org.id,role:user.role,name:user.name,email:user.email});res.status(201).json({token,user,organization:org,property:prop})}catch(e){await client.query('ROLLBACK');res.status(409).json({error:'registration_failed'})}finally{client.release()}});
app.post('/api/auth/login',async(req,res)=>{const em=email(req.body.email),password=String(req.body.password||'');const r=await q('SELECT id,organization_id,name,email,password_hash,role FROM users WHERE email=$1 AND active=true LIMIT 1',[em]);if(!r.rowCount||!checkPassword(password,r.rows[0].password_hash))return res.status(401).json({error:'invalid_credentials'});const u=r.rows[0];res.json({token:signToken({id:u.id,org:u.organization_id,role:u.role,name:u.name,email:u.email}),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));

app.get('/api/properties',auth,async(req,res)=>{const r=await q('SELECT * FROM properties WHERE organization_id=$1 AND active=true ORDER BY name',[req.user.org]);res.json(r.rows)});
app.get('/api/dashboard',auth,async(req,res)=>{const p=(await q('SELECT id,name FROM properties WHERE organization_id=$1 AND active=true ORDER BY name LIMIT 1',[req.user.org])).rows[0];if(!p)return res.json({});const [rooms,resv,income,guests,tasks]=await Promise.all([q("SELECT count(*) total,count(*) FILTER(WHERE status='occupied') occupied,count(*) FILTER(WHERE status='available') available,count(*) FILTER(WHERE status='cleaning') cleaning,count(*) FILTER(WHERE status='maintenance') maintenance FROM rooms WHERE property_id=$1 AND active=true",[p.id]),q("SELECT count(*) FILTER(WHERE status NOT IN('cancelled','checked_out','no_show')) active,count(*) FILTER(WHERE check_in=current_date AND status IN('confirmed','hold')) arrivals,count(*) FILTER(WHERE check_out=current_date AND status IN('confirmed','checked_in')) departures,coalesce(sum(total) FILTER(WHERE created_at>=date_trunc('month',now())),0) revenue FROM reservations WHERE property_id=$1",[p.id]),q("SELECT coalesce(sum(amount),0) total FROM ledger_entries WHERE organization_id=$1 AND kind='income' AND occurred_on>=date_trunc('month',current_date)",[req.user.org]),q('SELECT count(*) total FROM guests WHERE organization_id=$1',[req.user.org]),q("SELECT count(*) total,count(*) FILTER(WHERE status='pending') pending FROM housekeeping_tasks WHERE property_id=$1 AND created_at::date=current_date",[p.id])]);const rm=rooms.rows[0],rv=resv.rows[0];res.json({property:p,rooms:{...rm,total:Number(rm.total),occupied:Number(rm.occupied),available:Number(rm.available)},reservations:{active:Number(rv.active),arrivals:Number(rv.arrivals),departures:Number(rv.departures),revenue:Number(rv.revenue)},ledgerIncome:Number(income.rows[0].total),guests:Number(guests.rows[0].total),housekeeping:{total:Number(tasks.rows[0].total),pending:Number(tasks.rows[0].pending)}})});

app.get('/api/rooms',auth,async(req,res)=>{const r=await q('SELECT r.*,rt.name room_type,rt.capacity,rt.base_rate FROM rooms r JOIN room_types rt ON rt.id=r.room_type_id JOIN properties p ON p.id=r.property_id WHERE p.organization_id=$1 AND r.active=true ORDER BY p.name,r.number',[req.user.org]);res.json(r.rows)});
app.patch('/api/rooms/:id',auth,async(req,res)=>{const allowed=['available','occupied','cleaning','maintenance','blocked'];const s=clean(req.body.status,30);if(!allowed.includes(s))return res.status(400).json({error:'invalid_status'});const r=await q('UPDATE rooms SET status=$1 WHERE id=$2 AND property_id IN(SELECT id FROM properties WHERE organization_id=$3) RETURNING *',[s,req.params.id,req.user.org]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'room.status','room',req.params.id,{status:s});res.json(r.rows[0])});

app.get('/api/guests',auth,async(req,res)=>{const term=clean(req.query.q,100);const r=await q('SELECT * FROM guests WHERE organization_id=$1 AND ($2="" OR full_name ILIKE $3 OR email ILIKE $3 OR phone ILIKE $3) ORDER BY created_at DESC LIMIT 100',[req.user.org,term,`%${term}%`]);res.json(r.rows)});
app.post('/api/guests',auth,async(req,res)=>{const name=clean(req.body.fullName,160);if(name.length<2)return res.status(400).json({error:'name_required'});const r=await q('INSERT INTO guests(organization_id,full_name,email,phone,country_code,document_last4,notes,marketing_opt_in) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[req.user.org,name,email(req.body.email)||null,clean(req.body.phone,40)||null,clean(req.body.countryCode,8)||null,clean(req.body.documentLast4,4)||null,clean(req.body.notes,1000),Boolean(req.body.marketingOptIn)]);await audit(req,'guest.create','guest',r.rows[0].id);res.status(201).json(r.rows[0])});

app.get('/api/reservations',auth,async(req,res)=>{const r=await q(`SELECT r.*,g.full_name guest_name,rm.number room_number,rt.name room_type FROM reservations r JOIN guests g ON g.id=r.guest_id LEFT JOIN reservation_rooms rr ON rr.reservation_id=r.id LEFT JOIN rooms rm ON rm.id=rr.room_id LEFT JOIN room_types rt ON rt.id=rm.room_type_id JOIN properties p ON p.id=r.property_id WHERE r.organization_id=$1 AND ($2='' OR g.full_name ILIKE $3 OR r.confirmation_code ILIKE $3 OR rm.number ILIKE $3) ORDER BY r.check_in DESC,r.created_at DESC LIMIT 250`,[req.user.org,clean(req.query.q,100),`%${clean(req.query.q,100)}%`]);res.json(r.rows)});
app.post('/api/reservations',auth,async(req,res)=>{const {propertyId,roomId,guestId,checkIn,checkOut}=req.body;const adults=Math.max(1,Number(req.body.adults||1)),children=Math.max(0,Number(req.body.children||0)),rate=Number(req.body.rate||0),tax=Number(req.body.tax||0);if(!propertyId||!roomId||!guestId||!/^\d{4}-\d{2}-\d{2}$/.test(checkIn||'')||!/^\d{4}-\d{2}-\d{2}$/.test(checkOut||'')||new Date(checkOut)<=new Date(checkIn))return res.status(400).json({error:'invalid_reservation'});const overlap=await q(`SELECT 1 FROM reservation_rooms rr JOIN reservations r ON r.id=rr.reservation_id WHERE rr.room_id=$1 AND r.status NOT IN('cancelled','checked_out','no_show') AND r.check_in < $3 AND r.check_out > $2 LIMIT 1`,[roomId,checkIn,checkOut]);if(overlap.rowCount)return res.status(409).json({error:'room_unavailable'});const code='JS-'+new Date().getFullYear()+'-'+crypto.randomBytes(4).toString('hex').toUpperCase();const total=rate+tax;const client=await pool.connect();try{await client.query('BEGIN');const v=(await client.query(`INSERT INTO reservations(organization_id,property_id,guest_id,confirmation_code,check_in,check_out,adults,children,channel,currency,subtotal,tax,total,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[req.user.org,propertyId,guestId,code,checkIn,checkOut,adults,children,clean(req.body.channel,30)||'direct','BRL',rate,tax,total,clean(req.body.notes,1000)])).rows[0];await client.query('INSERT INTO reservation_rooms(reservation_id,room_id,rate) VALUES($1,$2,$3)',[v.id,roomId,rate]);await client.query("UPDATE rooms SET status=CASE WHEN status='available' THEN 'available' ELSE status END WHERE id=$1",[roomId]);await client.query('COMMIT');await audit(req,'reservation.create','reservation',v.id,{code});res.status(201).json(v)}catch(e){await client.query('ROLLBACK');res.status(500).json({error:'reservation_failed'})}finally{client.release()}});
app.patch('/api/reservations/:id/status',auth,async(req,res)=>{const allowed=['hold','confirmed','checked_in','checked_out','cancelled','no_show'];const s=clean(req.body.status,30);if(!allowed.includes(s))return res.status(400).json({error:'invalid_status'});const r=await q('UPDATE reservations SET status=$1 WHERE id=$2 AND organization_id=$3 RETURNING *',[s,req.params.id,req.user.org]);if(!r.rowCount)return res.status(404).json({error:'not_found'});if(s==='cancelled'||s==='checked_out'||s==='no_show'){await q("UPDATE rooms SET status='available' WHERE id=(SELECT room_id FROM reservation_rooms WHERE reservation_id=$1)",[req.params.id])}await audit(req,'reservation.status','reservation',req.params.id,{status:s});res.json(r.rows[0])});

app.get('/api/housekeeping',auth,async(req,res)=>{const r=await q("SELECT h.*,rm.number room_number,u.name assignee FROM housekeeping_tasks h LEFT JOIN rooms rm ON rm.id=h.room_id LEFT JOIN users u ON u.id=h.assigned_to JOIN properties p ON p.id=h.property_id WHERE p.organization_id=$1 ORDER BY h.created_at DESC LIMIT 250",[req.user.org]);res.json(r.rows)});
app.post('/api/housekeeping',auth,async(req,res)=>{const r=await q('INSERT INTO housekeeping_tasks(property_id,room_id,type,priority,notes) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM properties WHERE id=$1 AND organization_id=$6) RETURNING *',[req.body.propertyId,req.body.roomId||null,clean(req.body.type,30)||'cleaning',clean(req.body.priority,20)||'normal',clean(req.body.notes,1000),req.user.org]);if(!r.rowCount)return res.status(400).json({error:'invalid_property'});res.status(201).json(r.rows[0])});
app.patch('/api/housekeeping/:id',auth,async(req,res)=>{const status=clean(req.body.status,30);const r=await q("UPDATE housekeeping_tasks SET status=$1,completed_at=CASE WHEN $1='completed' THEN now() ELSE NULL END WHERE id=$2 AND property_id IN(SELECT id FROM properties WHERE organization_id=$3) RETURNING *",[status,req.params.id,req.user.org]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])});

app.get('/api/finance/ledger',auth,async(req,res)=>{const r=await q('SELECT * FROM ledger_entries WHERE organization_id=$1 ORDER BY occurred_on DESC,created_at DESC LIMIT 500',[req.user.org]);res.json(r.rows)});
app.post('/api/finance/ledger',auth,role('owner','admin','manager','finance'),async(req,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'invalid_amount'});const r=await q('INSERT INTO ledger_entries(organization_id,property_id,reservation_id,kind,category,description,amount,currency,occurred_on) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.user.org,req.body.propertyId||null,req.body.reservationId||null,req.body.kind==='expense'?'expense':'income',clean(req.body.category,80),clean(req.body.description,200),amount,'BRL',req.body.occurredOn||new Date().toISOString().slice(0,10)]);await audit(req,'ledger.create','ledger',r.rows[0].id);res.status(201).json(r.rows[0])});

app.get('/api/audit',auth,role('owner','admin'),async(req,res)=>{const r=await q('SELECT id,action,entity,entity_id,metadata,ip,created_at FROM audit_log WHERE organization_id=$1 ORDER BY id DESC LIMIT 500',[req.user.org]);res.json(r.rows)});
app.get('/api/export/reservations.csv',auth,async(req,res)=>{const r=await q('SELECT confirmation_code,guest_id,check_in,check_out,status,channel,total,currency FROM reservations WHERE organization_id=$1 ORDER BY check_in DESC LIMIT 5000',[req.user.org]);const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=['confirmation_code,guest_id,check_in,check_out,status,channel,total,currency',...r.rows.map(x=>[x.confirmation_code,x.guest_id,x.check_in,x.check_out,x.status,x.channel,x.total,x.currency].map(esc).join(','))].join('\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="jarastay-reservations.csv"');res.send('\ufeff'+csv)});

app.post('/api/public/booking',async(req,res)=>{const {propertyId,roomId,checkIn,checkOut}=req.body;const client=await pool.connect();try{await client.query('BEGIN');const p=(await client.query('SELECT id,organization_id FROM properties WHERE id=$1 AND active=true',[propertyId])).rows[0];if(!p)throw new Error('property');const overlap=await client.query(`SELECT 1 FROM reservation_rooms rr JOIN reservations r ON r.id=rr.reservation_id WHERE rr.room_id=$1 AND r.status NOT IN('cancelled','checked_out','no_show') AND r.check_in < $3 AND r.check_out > $2 LIMIT 1`,[roomId,checkIn,checkOut]);if(overlap.rowCount){await client.query('ROLLBACK');return res.status(409).json({error:'room_unavailable'})}const g=(await client.query('INSERT INTO guests(organization_id,full_name,email,phone,marketing_opt_in) VALUES($1,$2,$3,$4,$5) RETURNING id',[p.organization_id,clean(req.body.fullName,160),email(req.body.email)||null,clean(req.body.phone,40)||null,Boolean(req.body.marketingOptIn)])).rows[0];const rt=(await client.query('SELECT rt.base_rate FROM rooms rm JOIN room_types rt ON rt.id=rm.room_type_id WHERE rm.id=$1',[roomId])).rows[0];if(!rt)throw new Error('room');const rate=Number(rt.base_rate);const code='WEB-'+crypto.randomBytes(5).toString('hex').toUpperCase();const r=(await client.query(`INSERT INTO reservations(organization_id,property_id,guest_id,confirmation_code,check_in,check_out,adults,children,channel,currency,subtotal,total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'website','BRL',$9,$9) RETURNING confirmation_code,check_in,check_out,total`,[p.organization_id,p.id,g.id,code,checkIn,checkOut,Number(req.body.adults||1),Number(req.body.children||0),rate])).rows[0];await client.query('INSERT INTO reservation_rooms(reservation_id,room_id,rate) VALUES((SELECT id FROM reservations WHERE confirmation_code=$1),$2,$3)',[code,roomId,rate]);await client.query('COMMIT');res.status(201).json({reservation:r})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'booking_failed'})}finally{client.release()}});

app.get('*',(req,res)=>res.sendFile(path.join(publicDir,'index.html')));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'internal_error'})});
app.listen(port,()=>console.log(`JaraStay listening on :${port}`));
